version: '3.3'
services:
  zoraxy-docker:
    image: ghcr.io/barto95100/zoraxy-dns-challenge:v3.0.3
    container_name: ${nom_container}
    ports:
      - ${port_http}:80
      - ${port_https}:443
      - ${port_admin}:8000
    volumes:
      - ${dossier_config}/conf:/opt/zoraxy/config/
    environment:
      ARGS: '-fastgeoip=true'
