version: '3.3'
services:
  zoraxy-docker:
    image: ghcr.io/barto95100/zoraxy-dns-challenge:v3.0.3
    container_name: ${name_container}
    ports:
      - 80:80
      - 443:443
      - ${ports}:8000
    volumes:
      - ${folder}/conf:/opt/zoraxy/config/
    environment:
      ARGS: '-fastgeoip=true'
