version: "3"
services:
  db:
    image: postgres:latest
    container_name: ${nom_container}
    environment:
      POSTGRES_DB: ${db_name}
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_USER: ${db_user}
    ports:
      - ${port}:8080
    volumes:
      - ${dossier}/data:/var/lib/postgresql/data
    logging:
      driver: "none"
    restart: unless-stopped