version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "${port}:80/tcp"
    environment:
      TZ: 'Europe/Paris'
      WEBPASSWORD: ${mot_de_passe}
    volumes:
      - ${dossier}/etc-pihole:/etc/pihole'
      - ${dossier}/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped