version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: ${nom_container}
    ports:
      - ${port}:3000
    volumes:
      - ${dossier}/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro