### ADguard
version: "3"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: ${nom_container}
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ${dossier}/work:/opt/adguardhome/work
      - ${dossier}/config:/opt/adguardhome/conf
    restart: unless-stopped