version: "3.9"
services:
  excalidraw:
    container_name: ${nom_container}
    healthcheck:
     test: curl -f http://localhost:80/ || exit 1
    image: excalidraw/excalidraw:latest
    ports:
      - ${port}:80
    restart: on-failure:5
    stdin_open: true
    environment:
      - NODE_ENV=production