version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - ${port_http}:80
      - ${port_https}:443
      - ${port_admin}:81
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "${db_user}"
      DB_MYSQL_PASSWORD: "${db_password}"
      DB_MYSQL_NAME: "${db_name}"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ${dossier}/data:/data
      - ${dossier}/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${db_password_admin}'
      MYSQL_DATABASE: '${db_name}'
      MYSQL_USER: '${db_user}'
      MYSQL_PASSWORD: '${db_password}'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - ${dossier}/mysql:/var/lib/mysql